name: ribo
channels:
    - conda-forge
    - defaults
    - bioconda
    - cyclus
dependencies:
    - python>=3.6
    - samtools>=1.4
    - setuptools
    - pip
    - numpy>=1.9
    - pandas>=0.24.1
    - matplotlib>=3.0.2
    - pysam>=0.15.0
    - bedtools>=2.27.1
    - h5py>=2.9.0
    - click==7.0
    - multiprocess>=0.70.7
    - pyyaml>=5.1
